# Generated by Django 3.2.6 on 2022-08-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_log_acciones_lg_cseccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categariaproducto',
            name='CP_NHABILITADO',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='CT_NHABILITADO',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
    ]
