# Generated by Django 3.2.6 on 2022-09-10 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_producto_pc_ncalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productor',
            name='CT_NID',
        ),
        migrations.AddField(
            model_name='contrato',
            name='PR_NID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='USUARIO_PRODUCTOR', to='home.productor'),
            preserve_default=False,
        ),
    ]
