# Generated by Django 3.2.6 on 2022-09-10 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220910_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='CP_NID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='CATEGORIAPRODUCTO', to='home.categariaproducto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='PR_NID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='FK_PRODUCTOR', to='home.productor'),
            preserve_default=False,
        ),
    ]
