# Generated by Django 3.2.6 on 2022-09-11 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_auto_20220910_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='DESPACHO',
            fields=[
                ('DE_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID DESPACHO')),
                ('DE_CESTADO', models.CharField(blank=True, max_length=32, null=True, verbose_name='ESTADO')),
                ('DE_FFECHA_CREACION', models.DateTimeField(verbose_name='FECHA CREACION')),
                ('DE_FFECHA_ENTREGA', models.DateTimeField(verbose_name='FECHA ENTREGA')),
                ('DE_NPROCESADO', models.BooleanField(blank=True, default=False, null=True, verbose_name='HABILITADO')),
            ],
            options={
                'db_table': 'DESPACHO',
            },
        ),
        migrations.CreateModel(
            name='DIRECCION',
            fields=[
                ('DR_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id Direccion')),
                ('DR_CNOMBRE', models.CharField(max_length=1024, verbose_name='Nombre')),
                ('DR_CCALLE', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Calle')),
                ('DR_CNUMERO', models.CharField(blank=True, max_length=32, null=True, verbose_name='Numero')),
                ('DR_CTELEFONO1', models.CharField(max_length=32, verbose_name='Telefono 1 ')),
                ('DR_CTELEFONO2', models.CharField(max_length=32, verbose_name='Telefono 2 ')),
                ('DR_NHABILITADO', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('US_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Id Socio Negocio')),
            ],
            options={
                'db_table': 'DIRECCION',
            },
        ),
        migrations.CreateModel(
            name='ORDEN_VENTA',
            fields=[
                ('OV_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID ORDEN DE VENTA')),
                ('OV_CESTADO', models.CharField(blank=True, max_length=32, null=True, verbose_name='ESTADO')),
                ('OV_FFECHA_CREACION', models.DateTimeField(verbose_name='FECHA CREACION')),
                ('OV_NPROCESADO', models.BooleanField(blank=True, default=False, null=True, verbose_name='HABILITADO')),
                ('DR_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.direccion', verbose_name='ID DIRECCION ORDEN DE VENTA')),
            ],
            options={
                'db_table': 'ORDEN_VENTA',
            },
        ),
        migrations.CreateModel(
            name='SOLICITUD_COMPRA',
            fields=[
                ('SC_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID SOLICITUD')),
                ('SC_FFECHA_CREACION', models.DateTimeField(verbose_name='FECHA CREACION')),
                ('SC_FFECHA_PROCESAMIENTO', models.DateTimeField(verbose_name='FECHA PROCESAMIENTO')),
                ('SC_NPROCESADO', models.BooleanField(blank=True, default=False, null=True, verbose_name='Habilitado')),
                ('SCD_NMONTO_TOTAL', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='MONTO TOTAL')),
                ('DR_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.direccion', verbose_name='ID DIRECCION SOLICITUD')),
            ],
            options={
                'db_table': 'SOLICITUD_COMPRA',
            },
        ),
        migrations.CreateModel(
            name='TIPO_CAMBIO',
            fields=[
                ('TC_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID ORDEN DE VENTA')),
                ('TC_CMONEDA', models.CharField(blank=True, max_length=32, null=True, verbose_name='Numero')),
                ('TC_NCONVERSION', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='CONVERSION')),
            ],
            options={
                'db_table': 'TIPO_CAMBIO',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='PC_NREFRIGERACION',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='REFRIGERACION'),
        ),
        migrations.CreateModel(
            name='TRANSPORTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TRA_NCARGA', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='CARGA TOTAL')),
                ('TRA_NREFRIGERACION', models.BooleanField(blank=True, default=True, null=True, verbose_name='Habilitado')),
                ('TRA_CMARCA', models.CharField(max_length=128, verbose_name='MARCA')),
                ('TRA_CMODELO', models.CharField(max_length=128, verbose_name='MODELO')),
                ('TRA_CPATENTE', models.CharField(max_length=128, verbose_name='PATENTE')),
                ('TRA_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.transportista', verbose_name='USUARIO_TRANSPORTISTA')),
            ],
            options={
                'db_table': 'TRANSPORTE',
            },
        ),
        migrations.CreateModel(
            name='SUBASTA_DETALLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUD_NCOBRO', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='PRECIO')),
                ('TRA_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.transporte', verbose_name='ID TRANSPORTE')),
                ('TR_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.transportista', verbose_name='ID DIRECCION SUBASTA')),
            ],
            options={
                'db_table': 'SUBASTA_DETALLE',
            },
        ),
        migrations.CreateModel(
            name='SUBASTA',
            fields=[
                ('SU_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID ORDEN DE VENTA SUBASTA')),
                ('SU_FFECHA_INICIO', models.DateTimeField(verbose_name='FECHA INICIO')),
                ('SU_FFECHA_TERMINO', models.DateTimeField(verbose_name='FECHA TERMINO')),
                ('SU_PESO_TOTAL', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='PRECIO')),
                ('SU_NREFRIGERACION', models.BooleanField(blank=True, default=False, null=True, verbose_name='REFRIGERACION')),
                ('DR_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.direccion', verbose_name='ID DIRECCION SUBASTA')),
                ('US_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ID DIRECCION SUBASTA')),
            ],
            options={
                'db_table': 'SUBASTA',
            },
        ),
        migrations.CreateModel(
            name='STOCK',
            fields=[
                ('STK_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('STK_NQTY', models.IntegerField(verbose_name='Valor Transacción')),
                ('PC_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.producto', verbose_name='ID Item')),
            ],
            options={
                'db_table': 'STOCK',
            },
        ),
        migrations.CreateModel(
            name='SOLICITUD_COMPRA_DETALLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SC_NLINEA', models.IntegerField(verbose_name='Numero De Linea')),
                ('SCD_NQTY', models.IntegerField(verbose_name='CANTIDAD')),
                ('SCD_NPRECIO', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='PRECIO')),
                ('SCD_NMONTO', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='MONTO TOTAL')),
                ('PC_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.producto', verbose_name='ID PRODUCTO SCD')),
                ('SC_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.solicitud_compra', verbose_name='ID SOLICITUD DETALLE')),
            ],
            options={
                'db_table': 'SOLICITUD_COMPRA_DETALLE',
            },
        ),
        migrations.AddField(
            model_name='solicitud_compra',
            name='TC_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.tipo_cambio', verbose_name='ID TIPO CAMBIO SOLICITUD'),
        ),
        migrations.AddField(
            model_name='solicitud_compra',
            name='US_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ID USUARIO SOLICITUD'),
        ),
        migrations.CreateModel(
            name='ORDEN_VENTA_DETALLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OVD_NQTY', models.IntegerField(verbose_name='CANTIDAD')),
                ('OVD_NLINEA', models.IntegerField(verbose_name='Numero De Linea')),
                ('OVD_NPRECIO', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='PRECIO')),
                ('OVD_NMONTO', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='MONTO TOTAL')),
                ('OV_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.orden_venta', verbose_name='ID SOLICITUD OVD')),
                ('PC_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.producto', verbose_name='ID PRODUCTO OVD')),
            ],
            options={
                'db_table': 'ORDEN_VENTA_DETALLE',
            },
        ),
        migrations.AddField(
            model_name='orden_venta',
            name='TC_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.tipo_cambio', verbose_name='ID TIPO CAMBIO ORDEN DE VENTA'),
        ),
        migrations.AddField(
            model_name='orden_venta',
            name='US_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ID USUARIO ORDEN DE VENTA'),
        ),
        migrations.CreateModel(
            name='KARDEX',
            fields=[
                ('KX_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('KX_FFECHA_REGISTRO', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('KX_CTIPODOC', models.CharField(max_length=50, verbose_name='Tipo Documento')),
                ('KX_NNUMERDOC', models.BigIntegerField(verbose_name='Número Documento')),
                ('KX_FFECHADOC', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Documento')),
                ('KX_CES', models.CharField(max_length=50, verbose_name='E/S')),
                ('KX_NQTYTRANS', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='Cantidad Transacción')),
                ('KX_NCOSTOTRANS', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='Costo Transacción')),
                ('KX_NVALORTRANS', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='Valor Transacción')),
                ('KX_NQTYACUM', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='Cantidad Acumulada')),
                ('KX_NVALORACUM', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='Valor Acumulado')),
                ('KX_NPRECIOPROMEDIO', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='Precio Promedio')),
                ('KX_NDIA', models.BigIntegerField(verbose_name='DIA Documento')),
                ('KX_NMES', models.BigIntegerField(verbose_name='MES Documento')),
                ('KX_NAÑO', models.BigIntegerField(verbose_name='AÑO Documento')),
                ('PC_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.producto', verbose_name='ID Item')),
            ],
            options={
                'db_table': 'KARDEX',
            },
        ),
        migrations.CreateModel(
            name='DESPACHO_DETALLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DED_NQTY', models.IntegerField(verbose_name='CANTIDAD')),
                ('DED_NLINEA', models.IntegerField(verbose_name='Numero De Linea')),
                ('DED_NPRECIO', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='PRECIO')),
                ('DED_NMONTO', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='MONTO TOTAL')),
                ('DE_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.despacho', verbose_name='ID SOLICITUD DED')),
                ('PC_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.producto', verbose_name='ID PRODUCTO DED ')),
            ],
            options={
                'db_table': 'DESPACHO_DETALLE',
            },
        ),
        migrations.AddField(
            model_name='despacho',
            name='DR_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.direccion', verbose_name='ID DIRECCION DESPACHO'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='TC_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.tipo_cambio', verbose_name='ID TIPO CAMBIO DESPACHO'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='US_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ID USUARIO DESPACHO'),
        ),
        migrations.CreateModel(
            name='CARRO_COMPRA',
            fields=[
                ('CC_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID CARRO COMPRA')),
                ('CC_NQTY', models.IntegerField(verbose_name='CANTIDAD')),
                ('CC_NPRECIO', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='PRECIO')),
                ('CC_NMONTO_TOTAL', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='MONTO TOTAL')),
                ('PC_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.producto', verbose_name='ID PRODUCTO CARRO COMPRA')),
                ('US_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ID USUARIO CARRO COMPRA')),
            ],
            options={
                'db_table': 'CARRO_COMPRA',
            },
        ),
    ]
