# Generated by Django 4.0.4 on 2022-09-29 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220910_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='CARRITO',
            fields=[
                ('ID_CARRITO', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_USUARIO', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.users_extension')),
            ],
            options={
                'db_table': 'CARRITO',
            },
        ),
    ]
