# Generated by Django 3.2.6 on 2022-09-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220911_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='PC_NREFRIGERACION',
            field=models.BooleanField(default=False, verbose_name='REFRIGERACION'),
        ),
    ]
