# Generated by Django 4.0.4 on 2022-09-29 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='ID_USUARIO',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
