# Generated by Django 3.2.6 on 2022-09-12 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_producto_pc_nrefrigeracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='PR_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FK_PRODUCTOR', to='home.productor'),
        ),
    ]
