# Generated by Django 4.1 on 2022-09-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_producto_pr_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='PC_FOTO',
            field=models.ImageField(blank=True, null=True, upload_to='PRODUCTO/', verbose_name='Foto del Producto'),
        ),
    ]
