# Generated by Django 4.0.4 on 2022-10-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_carrito_id_usuario'),
        ('home', '0014_alter_producto_pr_nid'),
    ]

    operations = [
    ]
