# Generated by Django 4.0.4 on 2022-10-05 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_merge_20221004_2219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CARRITO',
        ),
    ]
