# Generated by Django 4.1 on 2022-09-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_producto_pc_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='PC_FOTO',
            field=models.ImageField(blank=True, null=True, upload_to='PRODUCTO/', verbose_name='Foto del producto'),
        ),
    ]
