# Generated by Django 4.1 on 2022-10-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_producto_pc_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='PC_FOTO',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/', verbose_name='Foto del producto'),
        ),
    ]
