# Generated by Django 4.0.4 on 2022-10-05 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_carrito'),
        ('home', '0021_alter_producto_pc_foto'),
    ]

    operations = [
    ]
