# Generated by Django 4.1 on 2022-10-13 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_merge_0016_delete_carrito_0021_alter_producto_pc_foto'),
        ('home', '0023_alter_producto_pc_foto'),
    ]

    operations = [
    ]
