# Generated by Django 3.2.6 on 2022-10-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_merge_20221012_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='PC_NPRECIO',
            field=models.DecimalField(decimal_places=5, max_digits=18, verbose_name='Precio'),
        ),
    ]
