# Generated by Django 4.1 on 2022-11-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_merge_20221012_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_extension',
            name='UX_CCORREO',
            field=models.CharField(max_length=128, null=True, verbose_name='Correo'),
        ),
    ]
