# Generated by Django 3.2.6 on 2022-10-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_producto_pc_nprecio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_compra',
            name='SC_FFECHA_PROCESAMIENTO',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FECHA PROCESAMIENTO'),
        ),
    ]
