# Generated by Django 3.2.6 on 2022-10-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_solicitud_compra_sc_ffecha_procesamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro_compra',
            name='CC_NESTADO',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ESTADO'),
        ),
    ]
