# Generated by Django 3.2.6 on 2022-10-31 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_orden_venta_ov_ctipo_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_venta',
            name='OV_NDOCUMENTO_ORIGEN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.solicitud_compra', verbose_name='Documento origen'),
        ),
    ]
