# Generated by Django 3.2.6 on 2022-11-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_orden_venta_ov_ndocumento_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_venta',
            name='OV_COBSERVACIONES',
            field=models.CharField(default=1, max_length=100, verbose_name='Observaciones'),
            preserve_default=False,
        ),
    ]
