# Generated by Django 3.2.6 on 2022-11-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_orden_venta_ov_cobservaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro_compra',
            name='CC_NMONTO_TOTAL',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True, verbose_name='MONTO TOTAL'),
        ),
        migrations.AlterField(
            model_name='carro_compra',
            name='CC_NPRECIO',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True, verbose_name='PRECIO'),
        ),
    ]
