# Generated by Django 3.2.6 on 2022-11-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20221101_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='categariaproducto',
            name='CP_FOTO',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
