# Generated by Django 3.2.6 on 2022-11-02 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_categariaproducto_cp_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro_compra',
            name='CP_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.categariaproducto', verbose_name='CATEGORIA PRODUCTO'),
        ),
        migrations.AddField(
            model_name='orden_venta_detalle',
            name='CP_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.categariaproducto', verbose_name='CATEGORIA PRODUCTO'),
        ),
        migrations.AddField(
            model_name='solicitud_compra_detalle',
            name='CP_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.categariaproducto', verbose_name='CATEGORIA PRODUCTO'),
        ),
    ]
