# Generated by Django 3.2.6 on 2022-11-02 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20221101_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_compra_detalle',
            name='PC_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.producto', verbose_name='ID PRODUCTO SCD'),
        ),
    ]
