# Generated by Django 3.2.6 on 2022-11-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_producto_pc_ffecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_compra_detalle',
            name='SCD_NESTADO',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Habilitado'),
        ),
    ]
