# Generated by Django 3.2.6 on 2022-11-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_solicitud_compra_detalle_scd_nestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_venta_detalle',
            name='OVD_NMONTO',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True, verbose_name='MONTO TOTAL'),
        ),
    ]
