# Generated by Django 3.2.6 on 2022-11-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20221102_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_compra',
            name='SCD_NESTADO',
        ),
        migrations.AddField(
            model_name='solicitud_compra_detalle',
            name='SCD_NESTADO',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Habilitado'),
        ),
    ]
