# Generated by Django 4.1.3 on 2022-11-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20221102_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categariaproducto',
            name='CP_FOTO',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='PC_FOTO',
            field=models.ImageField(upload_to='images'),
        ),
    ]
