# Generated by Django 4.0.4 on 2022-11-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_categariaproducto_cp_foto_and_more'),
        ('home', '0043_auto_20221103_0112'),
    ]

    operations = [
    ]
