# Generated by Django 3.2.6 on 2022-11-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20221103_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subasta',
            old_name='OV_NDOCUMENTO_ORIGEN',
            new_name='SU_NDOCUMENTO_ORIGEN',
        ),
        migrations.AddField(
            model_name='subasta',
            name='SU_NPROCESADO',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='HABILITADO'),
        ),
        migrations.AddField(
            model_name='subasta_detalle',
            name='SUD_NSELECCION',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Seleccion'),
        ),
    ]
