# Generated by Django 3.2.6 on 2022-11-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20221103_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='SU_FFECHA_INICIO',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FECHA INICIO'),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='SU_FFECHA_TERMINO',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FECHA TERMINO'),
        ),
    ]
