# Generated by Django 3.2.6 on 2022-11-03 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20221103_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporte',
            name='TRA_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.transportista', verbose_name='USUARIO_TRANSPORTISTA'),
        ),
    ]
