# Generated by Django 3.2.6 on 2022-11-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_transporte_tra_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporte',
            name='TRA_NHABILITADO',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Habilitado'),
        ),
    ]
