# Generated by Django 3.2.6 on 2022-11-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_transporte_tra_nhabilitado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporte',
            old_name='TRA_NID',
            new_name='TR_NID',
        ),
    ]
