# Generated by Django 3.2.6 on 2022-11-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_rename_tra_nid_transporte_tr_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='SU_NESTADO',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='HABILITADO'),
        ),
        migrations.AlterModelTable(
            name='subasta',
            table='SUBASTA<',
        ),
    ]
