# Generated by Django 3.2.6 on 2022-11-03 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20221103_1811'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subasta',
            table='SUBASTA',
        ),
    ]
