# Generated by Django 3.2.6 on 2022-11-03 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_subasta_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='SU_NTRANSPORTE_SELECCIONADO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.transporte', verbose_name='Documento origen'),
        ),
    ]
