# Generated by Django 3.2.6 on 2022-11-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_subasta_su_ntransporte_seleccionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='STK_CBODEGA',
            field=models.CharField(default='INTERNA', max_length=100, verbose_name='BODEGA'),
            preserve_default=False,
        ),
    ]
