# Generated by Django 4.1.3 on 2022-11-03 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_categariaproducto_cp_foto_and_more'),
        ('home', '0051_subasta_su_ntransporte_seleccionado'),
    ]

    operations = [
    ]
