# Generated by Django 4.0.4 on 2022-11-04 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_merge_20221103_0349'),
        ('home', '0051_subasta_su_ntransporte_seleccionado'),
    ]

    operations = [
    ]
