# Generated by Django 3.2.6 on 2022-11-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_stock_stk_cbodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='SU_CTIPO_SOLICITUD',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='HABILITADO'),
        ),
    ]
