# Generated by Django 4.1.3 on 2022-11-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_merge_20221103_1950'),
        ('home', '0052_stock_stk_cbodega'),
    ]

    operations = [
    ]
