# Generated by Django 4.1 on 2022-11-04 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_users_extension_ux_ccorreo'),
        ('home', '0054_alter_stock_stk_cbodega'),
    ]

    operations = [
    ]
