# Generated by Django 4.1.3 on 2022-11-04 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_merge_0052_merge_20221103_1950_0052_stock_stk_cbodega'),
        ('home', '0054_alter_stock_stk_cbodega'),
    ]

    operations = [
    ]
