# Generated by Django 4.0.4 on 2022-11-04 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_merge_20221103_2209'),
        ('home', '0054_alter_stock_stk_cbodega'),
    ]

    operations = [
    ]
