# Generated by Django 3.2.6 on 2022-11-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_stock_stk_cbodega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='SU_CTIPO_SOLICITUD',
        ),
        migrations.AddField(
            model_name='solicitud_compra',
            name='SC_CTIPO_SOLICITUD',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones'),
        ),
    ]
