# Generated by Django 4.1.3 on 2022-11-04 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_auto_20221104_0010'),
        ('home', '0055_merge_20221103_2251'),
    ]

    operations = [
    ]
