# Generated by Django 3.2.6 on 2022-11-10 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0055_auto_20221104_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PA_OV_ORIGEN', models.IntegerField(verbose_name='CANTIDAD')),
                ('PA_FFECHA', models.DateTimeField(blank=True, null=True, verbose_name='FECHA INICIO')),
                ('PA_NPAGADO', models.BooleanField(blank=True, default=False, null=True, verbose_name='Seleccion')),
                ('PA_CCODIGO', models.CharField(blank=True, max_length=100, null=True, verbose_name='codigo')),
                ('US_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'db_table': 'PAGO',
            },
        ),
    ]
