# Generated by Django 3.2.6 on 2022-11-15 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0057_alter_pago_pa_ov_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAGO_CUENTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCA_FFECHA', models.DateTimeField(blank=True, null=True, verbose_name='FECHA INICIO')),
                ('PCA_NMONTO', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='PRECIO')),
                ('PCA_NQTY', models.IntegerField(verbose_name='Numero De Linea')),
                ('PA_CCODIGO', models.CharField(blank=True, max_length=100, null=True, verbose_name='codigo')),
                ('US_NID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'db_table': 'PAGO_CUENTA',
            },
        ),
    ]
