# Generated by Django 3.2.6 on 2022-11-24 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_pago_cuenta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago_cuenta',
            old_name='PCA_NMONTO',
            new_name='PCA_NPRECIO',
        ),
        migrations.RemoveField(
            model_name='pago_cuenta',
            name='PA_CCODIGO',
        ),
        migrations.AddField(
            model_name='pago_cuenta',
            name='PCA_OV_ORIGEN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.orden_venta', verbose_name='Orden de venta'),
        ),
        migrations.AlterField(
            model_name='pago_cuenta',
            name='PCA_NQTY',
            field=models.IntegerField(verbose_name='CANTIDAD'),
        ),
    ]
