# Generated by Django 4.0.4 on 2022-11-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_merge_20221104_0622'),
        ('home', '0059_auto_20221123_2350'),
    ]

    operations = [
    ]
