# Generated by Django 3.2.6 on 2022-11-25 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_merge_20221103_2313'),
        ('home', '0059_auto_20221123_2350'),
    ]

    operations = [
    ]
